// Server-Side Image Generator using Puppeteer
// This generates images server-side, which is much more reliable

import puppeteer from 'puppeteer';

export interface ServerImage {
  id: string;
  url: string;
  title: string;
  industry: string;
  generatedAt: string;
}

class ServerImageGenerator {
  private browser: any = null;

  async initialize() {
    if (!this.browser) {
      this.browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
    }
  }

  async generateImage(content: string, industry: string): Promise<ServerImage> {
    await this.initialize();
    
    const page = await this.browser.newPage();
    
    // Set viewport
    await page.setViewport({ width: 400, height: 300 });
    
    // Create HTML template
    const html = this.createHTMLTemplate(industry, content);
    
    // Set content
    await page.setContent(html);
    
    // Take screenshot
    const screenshot = await page.screenshot({
      type: 'png',
      fullPage: false
    });
    
    // Convert to base64
    const base64 = screenshot.toString('base64');
    const dataUrl = `data:image/png;base64,${base64}`;
    
    await page.close();
    
    return {
      id: `server_img_${Date.now()}`,
      url: dataUrl,
      title: `${industry} Business Solution`,
      industry: industry,
      generatedAt: new Date().toISOString()
    };
  }

  private createHTMLTemplate(industry: string, content: string): string {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {
                margin: 0;
                padding: 0;
                font-family: Arial, sans-serif;
                width: 400px;
                height: 300px;
                background: white;
            }
            .header {
                background: #e30613;
                color: white;
                padding: 15px 20px;
                height: 30px;
            }
            .logo {
                font-size: 24px;
                font-weight: bold;
                margin: 0;
            }
            .subtitle {
                font-size: 14px;
                margin: 5px 0 0 0;
                opacity: 0.9;
            }
            .content {
                padding: 20px;
                border: 2px solid #e30613;
                margin: 20px;
                height: 180px;
                border-radius: 8px;
            }
            .title {
                font-size: 18px;
                font-weight: bold;
                color: #1A1A1A;
                margin: 0 0 10px 0;
            }
            .description {
                font-size: 14px;
                color: #666666;
                margin: 0 0 10px 0;
            }
            .preview {
                font-size: 12px;
                color: #1A1A1A;
                margin: 0 0 15px 0;
                line-height: 1.4;
            }
            .badge {
                background: #e30613;
                color: white;
                padding: 5px 15px;
                border-radius: 4px;
                font-size: 12px;
                font-weight: bold;
                display: inline-block;
            }
            .footer {
                position: absolute;
                bottom: 10px;
                left: 20px;
                font-size: 10px;
                color: #666666;
            }
            .logo-circle {
                position: absolute;
                bottom: 20px;
                right: 20px;
                width: 50px;
                height: 50px;
                background: #e30613;
                border-radius: 50%;
                display: flex;
                align-items: center;
                justify-content: center;
                color: white;
                font-size: 16px;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1 class="logo">e& (Etisalat)</h1>
            <p class="subtitle">Business Solutions</p>
        </div>
        
        <div class="content">
            <h2 class="title">${industry.charAt(0).toUpperCase() + industry.slice(1)} Industry</h2>
            <p class="description">Transform your business with e& digital solutions</p>
            <p class="preview">${content.substring(0, 100)}...</p>
            <span class="badge">${industry.toUpperCase()}</span>
        </div>
        
        <div class="logo-circle">e&</div>
        
        <div class="footer">
            Generated by Jammy AI • ${new Date().toLocaleDateString()}
        </div>
    </body>
    </html>
    `;
  }

  async close() {
    if (this.browser) {
      await this.browser.close();
      this.browser = null;
    }
  }
}

export const serverImageGenerator = new ServerImageGenerator();
