// Ultra Simple Image Generator - Uses Canvas to create PNG images
// This is the most reliable approach for generating images

export interface SimpleImage {
  id: string;
  url: string;
  title: string;
  industry: string;
  generatedAt: string;
}

class UltraSimpleImageGenerator {
  // Generate a simple PNG image using canvas
  async generateImage(content: string, industry: string): Promise<SimpleImage> {
    // Create a simple canvas-based image
    const canvas = this.createCanvasImage(industry, content);
    const dataUrl = canvas.toDataURL('image/png');
    
    return {
      id: `img_${Date.now()}`,
      url: dataUrl,
      title: `${industry} Business Solution`,
      industry: industry,
      generatedAt: new Date().toISOString()
    };
  }

  private createCanvasImage(industry: string, content: string): HTMLCanvasElement {
    // Create canvas element
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    
    if (!ctx) {
      throw new Error('Canvas context not available');
    }

    // Set canvas size
    canvas.width = 400;
    canvas.height = 300;

    // Background
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(0, 0, 400, 300);

    // Header with e& branding
    ctx.fillStyle = '#e30613';
    ctx.fillRect(0, 0, 400, 60);

    // e& logo text
    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'bold 24px Arial';
    ctx.textAlign = 'left';
    ctx.fillText('e& (Etisalat)', 20, 35);

    // Business Solutions text
    ctx.font = '14px Arial';
    ctx.fillText('Business Solutions', 20, 50);

    // Main content area
    ctx.strokeStyle = '#e30613';
    ctx.lineWidth = 2;
    ctx.strokeRect(20, 80, 360, 180);

    // Industry title
    ctx.fillStyle = '#1A1A1A';
    ctx.font = 'bold 18px Arial';
    ctx.fillText(`${industry.charAt(0).toUpperCase() + industry.slice(1)} Industry`, 40, 110);

    // Description
    ctx.fillStyle = '#666666';
    ctx.font = '14px Arial';
    ctx.fillText('Transform your business with e& digital solutions', 40, 135);

    // Content preview (truncated)
    const preview = content.substring(0, 100) + '...';
    ctx.fillStyle = '#1A1A1A';
    ctx.font = '12px Arial';
    ctx.fillText(preview, 40, 155);

    // Industry badge
    ctx.fillStyle = '#e30613';
    ctx.fillRect(40, 170, 80, 25);
    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'bold 12px Arial';
    ctx.textAlign = 'center';
    ctx.fillText(industry.toUpperCase(), 80, 185);

    // e& logo circle
    ctx.fillStyle = '#e30613';
    ctx.beginPath();
    ctx.arc(320, 200, 25, 0, 2 * Math.PI);
    ctx.fill();
    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'bold 16px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('e&', 320, 205);

    // Footer
    ctx.fillStyle = '#666666';
    ctx.font = '10px Arial';
    ctx.textAlign = 'left';
    ctx.fillText(`Generated by Jammy AI • ${new Date().toLocaleDateString()}`, 20, 280);

    return canvas;
  }
}

export const ultraSimpleImageGenerator = new UltraSimpleImageGenerator();
